### ISSUE TITLE
Design of BufferedBlobIO is odd

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#46]
The design `BufferedBlobIO` is somewhat odd. The class introduce a buffer both for reads and writes. It looks like something that would be better handled by introducing a `BufferedStream` instead http://msdn.microsoft.com/en-us/library/system.io.bufferedstream%28v=vs.110%29.aspx

**Comment by Olxinos** [comment]
Well, i avoided streams because they tend to hide both the structure of the blob and what requests they do. I know it's a pretty bad idea to re-make what has already been done, but i found absolutely nothing on the msdn regarding their efficiency or their behaviour especially in edgecases. For instance if i seek i don't want the stream to try to check the size by retrieving it from the cloud, also i want to be sure that the server state is always coherent which can't be achieved unless i manage all the flushes manually. 
So i use the most basic operations instead.
Here, this specific class is supposed to minimize the loss of speed when sending multiple small packet (buffered output) while also minimizing the latency between the moment an event is pushed and the moment this event is readable (i suppose i have no guarantee regarding the frequence of buffer flushes). It could be done with two separate components (well classes, or whatever) but i felt like duplicating the data would be a bad idea.

**Comment by vermorel** [comment]
It's an unusual design pattern though. If you stand for it, then it should be documented.

**Comment by Olxinos** [comment]
I can't certify that my code is good, but i tried to document it, so i close the issue. Feel free to reopen it if the design is bothering you too much.
