### ISSUE TITLE
Remove unused History.Clear() method

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#47]
The method `History.Clear()` looks like a destructor implementation (not needed in C#). It's not even used. I suggest to remove this method.

**Comment by Olxinos** [comment]
Well it isn't really a destructor, it is here to reset the structure if we want to reuse it, it is also used by deserialize (though i don't like these methods).
I don't close the issue as even though it's not really dead code, i'm not satisfied with the code which uses it (plus, it isn't that critical since the structure is generally already empty when it's called).

**Comment by Olxinos** [comment]
The method has been removed.
